version: '3.8'

services:
  database:
    container_name: wtt-sf-database
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data:rw
